name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore CalculatorApp.sln

    - name: Build Solution
      run: msbuild CalculatorApp.sln /p:Configuration=Release

    - name: Run Tests
      # Эта команда найдет тесты, даже если они в другой версии .NET
      run: dotnet test --configuration Release --no-build
